### ISSUE TITLE
生成分片秘钥和签名时，ecdsa私钥会生成在内存中吗？

### ISSUE THREAD

**Issue by JacksonRGB** [gitzhou/threshold-signature-demo#1]
这套代码生成分片秘钥速度相比 https://github.com/binance-chain/tss-lib 和 https://github.com/ZenGo-X/multi-party-ecdsa 快很多。

论文看不太懂，想问一下，如果持有达到签名阈值个数的分片秘钥，能不能恢复出ecdsa私钥呢。

**Comment by gitzhou** [comment]
> 生成分片秘钥和签名时，ecdsa 私钥会生成在内存中吗

真正的私钥不论在分发时还是签名时，都不会存在于任何参与者的内存中，也无法被任何人计算。演示代码简化了 JVRSS 的通信过程。

> 如果持有达到签名阈值个数的分片秘钥，能不能恢复出 ecdsa 私钥呢

可以。Nakasendo 门限方案是 non-optimal 方案，恢复私钥需要 t 个私钥碎片，签名需要 2t+1 个私钥碎片，t 是多项式的次数，最小值为 1。

需要注意，签名时，2t+1 个参与者不是直接把自己的私钥碎片给协调员，让协调员（先恢复出私钥再）签名（这样协调员就知道真正的私钥了），而是每个人先用自己的碎片计算出签名碎片 (R, s)，协调员根据 2t+1 个 s 碎片，计算出最终的 S。
