### ISSUE TITLE
Etheruem Addition

### ISSUE THREAD

**Issue by zhen9999** [gitzhou/threshold-signature-demo#3]
Hi Gitzhou,

Could you provide some info / implementation of integrating Ethereum support into this?

Also please provide your ETH address, learnt a lot from this repo - would love to contribute something.

**Comment by gitzhou** [comment]
Hi zhen,

Sorry for not being familiar with ETH, so can't do anything about your proposal, yet it's great if you could open a PR to add more features.

And thank you very much for your donation if you like my work, my ETH address is

`0xF0e798713f5D5FC6E35743D0F0ae5308bB81b126`
